apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: amF4eWF6M24K
  CLOUDINARY_KEY: Nzg3NDExMjU4MzQ3MjUxCg==
  CLOUDINARY_SECRET: WEktakRkb3hCVVFOX0hETXV0bFlYMTRQSU5zCg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMmhoYVd0dGRYTjBZV1poTnpnaUxDSmhJam9pWTIxaGN6TXpiV1kyTUdnNWFESnJjMkUwZFdoamJqQnlaU0o5LlJZMjNvWmRvYmtQMk1NRTZDeVZxQ0EK
  DB_URL: bW9uZ29kYitzcnY6Ly9TYW1wYXRoOnNhbXBhdGgxMTIxQGNsdXN0ZXIwLnRxeTNjZWEubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjAK
